# Generated by Django 3.0.4 on 2020-04-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='corona',
            field=models.CharField(default='virus', max_length=200),
        ),
    ]
